const colors = {
	pirate: "#fc0041",
	navy: "#60fcf1",
	revo: "#6153CC",
	other: "#fbf706",
}

const charData = [{
	id: 1,
	name: "Mokey D. Luffy",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "East Blue",
	hairColor: "Preto",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/originals/f0/af/cb/f0afcbce7ed4a7df7b822964501bf995.jpg",
},
{
	id: 2,
	name: "Roronoa Zoro",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "East Blue",
	hairColor: "Verde",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "http://pm1.narvii.com/6410/dbe9b0b7d25624754f037bbb5a64fc3ef65ecc00_00.jpg",
},
{
	id: 3,
	name: "Nami",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "East Blue",
	hairColor: "Ruivo",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/736x/47/04/4e/47044e68d4f9f4ebb589d92576d5181b.jpg",
},
{
	id: 4,
	name: "Usopp",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "East Blue",
	hairColor: "Preto",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://pm1.narvii.com/6632/a9871fd10c48f429f18831c995999123755fe731_hq.jpg",
},
{
	id: 5,
	name: "Vinsmoke Sanji",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "North Blue",
	hairColor: "Loiro",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://uploads.spiritfanfiction.com/historias/capas/202104/deixada-por-ele--vinsmoke-sanji-22082031-120420211529.jpg",
},
{
	id: 6,
	name: "Nico Robin",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "West Blue",
	hairColor: "Preto",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/originals/7f/c0/8c/7fc08c65646aced80aa37ed3957ddf1d.jpg",
},
{
	id: 7,
	name: "Jinbe",
	specie: "Tritão",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Preto",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/originals/92/b2/4c/92b24c95f93d09cdef25ef3c0c3a3164.jpg",
},
{
	id: 8,
	name: "Arlong",
	specie: "Tritão",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Preto",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/originals/16/b5/ce/16b5ce60abb351ab4cdb8b9ebfbd6a76.jpg",
},
{
	id: 9,
	name: "Hatchan",
	specie: "Tritão",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Branco",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://ami.animecharactersdatabase.com/uploads/chars/thumbs/200/5688-1235316986.jpg",
},
{
	id: 10,
	name: "Fish Tiger",
	specie: "Tritão",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Preto",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/736x/21/7e/9b/217e9b8fbafecc843dc2209190e63902.jpg",
},
{
	id: 11,
	name: "Hody Jones",
	specie: "Tritão",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Preto",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "http://pm1.narvii.com/6356/55e24414a6ea93c9c995d690eacbbab86b706499_00.jpg",
},
{
	id: 12,
	name: "Sabo",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "East Blue",
	hairColor: "Loiro",
	occupation: "Revolucionário",
	weapons: "true",
	color: colors.revo,
	imgUrl: "https://www.comboinfinito.com.br/principal/wp-content/uploads/2019/09/One-Piece-3.jpg",
},
{
	id: 13,
	name: "Monkey D. Garp",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "East Blue",
	hairColor: "Branco",
	occupation: "Marinha",
	weapons: "false",
	color: colors.navy,
	imgUrl: "https://i.pinimg.com/1200x/4d/09/23/4d092374d3e0a0d92cb807a7f2a0a441.jpg",
},
{
	id: 14,
	name: "Carrot",
	specie: "Mink",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Loiro",
	occupation: "Outros",
	weapons: "false",
	color: colors.other,
	imgUrl: "https://criticalhits.com.br/wp-content/uploads/2022/04/carrot.jpg",
},
{
	id: 15,
	name: "Tom",
	specie: "Tritão",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Branco",
	occupation: "Outros",
	weapons: "false",
	color: colors.other,
	imgUrl: "https://www.personality-database.com/profile_images/164223.png",
},
{
	id: 16,
	name: "Smoker",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "East Blue",
	hairColor: "Branco",
	occupation: "Marinha",
	weapons: "true",
	color: colors.navy,
	imgUrl: "https://nntheblog.com/wp-content/uploads/2022/03/smoker-one-piece-12-1024x1024.jpg",
},
{
	id: 17,
	name: "Borsalino (Kizaru)",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "Grand Line",
	hairColor: "Preto",
	occupation: "Marinha",
	weapons: "false",
	color: colors.navy,
	imgUrl: "https://img1.ak.crunchyroll.com/i/spire4/dc74d400904ae57d6c2f12ad042350441555949693_full.png",
},
{
	id: 18,
	name: "Sakazuki (Akainu)",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "Grand Line",
	hairColor: "Preto",
	occupation: "Marinha",
	weapons: "false",
	color: colors.navy,
	imgUrl: "https://pbs.twimg.com/media/EfKdC1XX0AEvy-L.jpg:large",
},
{
	id: 19,
	name: "Kuzan (Aokiji)",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "South Blue",
	hairColor: "Preto",
	occupation: "Marinha",
	weapons: "false",
	color: colors.navy,
	imgUrl: "https://www.personality-database.com/profile_images/24556.png",
},
{
	id: 20,
	name: "Yamato",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Branco",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://selectgame.gamehall.com.br/wp-content/uploads/2022/02/Yamato-em-One-Piece-Episodio-1009-02.webp",
},
{
	id: 21,
	name: "Corazon",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "Novo Mundo",
	hairColor: "Loiro",
	occupation: "Marinha",
	weapons: "false",
	color: colors.navy,
	imgUrl: "https://i.pinimg.com/originals/8f/7d/50/8f7d50163ecfead22c1e2d96c5796dd1.jpg",
},
{
	id: 22,
	name: "Doflamingo",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "Novo Mundo",
	hairColor: "Loiro",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/736x/28/90/c0/2890c07ef2cdbf624c18225d9c1a016b.jpg",
},
{
	id: 23,
	name: "Shanks",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "West Blue",
	hairColor: "Ruivo",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/originals/ac/73/e0/ac73e0a96f5ef3bbabde03533df4dd7d.jpg",
},
{
	id: 24,
	name: "Marco",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "Novo Mundo",
	hairColor: "Loiro",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/564x/39/e5/5d/39e55d5e94880165f4f3102e36a8833f.jpg",
},
{
	id: 25,
	name: "Trafalgar D. Law",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "North Blue",
	hairColor: "Preto",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/originals/87/86/b9/8786b95e7d69a0493ae8da75b6c5fb2a.jpg",
},
{
	id: 26,
	name: "Eustass 'Captain' Kid",
	specie: "Humano",
	akumaNoMi: true,
	origin: "South Blue",
	hairColor: "Ruivo",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/736x/10/9d/53/109d535a623497b7a26e293b5f98db4e.jpg",
},
{
	id: 27,
	name: "Charlotte Katakuri",
	specie: "Humano",
	akumaNoMi: true,
	origin: "Novo Mundo",
	hairColor: "Ruivo",
	occupation: "Pirata",
	weapons: true,
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/736x/34/03/32/34033284474acbbe811f3b421b67e3fa.jpg",
},
{
	id: 28,
	name: "X-Drake",
	specie: "Humano",
	akumaNoMi: true,
	origin: "North Blue",
	hairColor: "Ruivo",
	occupation: "Marinha",
	weapons: true,
	color: colors.navy,
	imgUrl: "https://i.pinimg.com/736x/7e/fa/22/7efa2282f1abdd0774b5959109a5353b.jpg",
},
{
	id: 29,
	name: "Bartolomeo",
	specie: "Humano",
	akumaNoMi: true,
	origin: "East Blue",
	hairColor: "Verde",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://uploads.spiritfanfiction.com/historias/capitulos/201805/one-piece-arco-revolucionario-13063290-200520181246.jpg",
},
{
	id: 30,
	name: "Monet",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Verde",
	occupation: "Outros",
	weapons: true,
	color: colors.other,
	imgUrl: "https://cdn.myanimelist.net/r/360x360/images/characters/8/235837.jpg?s=38799c9bf47ff0564733a59269e9223c",
},
{
	id: 31,
	name: "Gaimon",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "East Blue",
	hairColor: "Verde",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://cdn.myanimelist.net/images/characters/11/384783.jpg",
},
{
	id: 32,
	name: "Pedro",
	specie: "Mink",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Loiro",
	occupation: "Pirata",
	weapons: true,
	color: colors.pirate,
	imgUrl: "https://pm1.narvii.com/6787/0f0cef91f137b5736fe55f8bd9a63c92ce17191ev2_hq.jpg",
},
{
	id: 33,
	name: "Boo Chinjao",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "West Blue",
	hairColor: "Ruivo",
	occupation: "Outros",
	weapons: true,
	color: colors.other,
	imgUrl: "https://assets.mycast.io/characters/boo-324032-normal.jpg?1572048815",
},
{
	id: 34,
	name: "Clover",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "West Blue",
	hairColor: "Verde",
	occupation: "Outros",
	weapons: "false",
	color: colors.other,
	imgUrl: "https://images.uncyc.org/pt/thumb/b/b1/Professor-Clover.jpg/200px-Professor-Clover.jpg",
},
{
	id: 35,
	name: "Nico Olvia",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "West Blue",
	hairColor: "Branco",
	occupation: "Outros",
	weapons: "false",
	color: colors.other,
	imgUrl: "https://pm1.narvii.com/6400/70c5b3f54e5fbae1abfd520cadfafaaf496284af_hq.jpg",
},
{
	id: 36,
	name: "Bartholomew Kuma",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "South Blue",
	hairColor: "Preto",
	occupation: "Revolucionário",
	weapons: "false",
	color: colors.revo,
	imgUrl: "https://i.pinimg.com/originals/53/50/08/53500815a24d77d37a95584e9e160553.png",
},
{
	id: 37,
	name: "Benn Beckman",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "North Blue",
	hairColor: "Branco",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://www.personality-database.com/profile_images/119020.png",
},
{
	id: 38,
	name: "Fukuro",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Verde",
	occupation: "Marinha",
	weapons: "false",
	color: colors.navy,
	imgUrl: "http://pm1.narvii.com/7123/f039b5efe6359f465145118e4e0971d11d149a48r1-225-350v2_00.jpg",
},
{
	id: 39,
	name: "Issho (Fujitora)",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Preto",
	occupation: "Marinha",
	weapons: "true",
	color: colors.navy,
	imgUrl: "https://i.pinimg.com/564x/0f/b2/41/0fb241fce5c4c6b8319332f9143b208d--one-piece.jpg",
},
{
	id: 40,
	name: "Basil Hawkins",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "North Blue",
	hairColor: "Loiro",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/originals/52/a1/53/52a1531ba458381b2e6046873737f1df.jpg",
},
{
	id: 41,
	name: "Bellamy",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "North Blue",
	hairColor: "Loiro",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://vignette.wikia.nocookie.net/onepiece/images/a/ab/Bellamy_Left_Scar.png/revision/latest?cb=20140916083625",
},
{
	id: 42,
	name: "Sarquiss",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "North Blue",
	hairColor: "Azul",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://pbs.twimg.com/media/Dy-kq3jWoAEPtpD.jpg",
},
{
	id: 43,
	name: "Miss GoldenWeek",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "North Blue",
	hairColor: "Ruivo",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://i0.wp.com/anime-planet.com/images/characters/miss-goldenweek-1016.jpg",
},
{
	id: 44,
	name: "Jaguar D. Saul",
	specie: "Gigante",
	akumaNoMi: "false",
	origin: "South Blue",
	hairColor: "Ruivo",
	occupation: "Marinha",
	weapons: "false",
	color: colors.navy,
	imgUrl: "https://i.skyrock.net/4735/49194735/pics/2023660277_small_1.jpg",
},
{
	id: 45,
	name: "Broggy",
	specie: "Gigante",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Loiro",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://cdn.anime-planet.com/characters/primary/broggy-1.jpg?t=1625772548",
},
{
	id: 46,
	name: "Dorry",
	specie: "Gigante",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Preto",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://1.bp.blogspot.com/-RblyxQxV-i4/UClJrSRhfmI/AAAAAAAAE3I/FKow79Zw6BY/s1600/Dorry.jpg",
},
{
	id: 47,
	name: "Little Oars Jr",
	specie: "Gigante",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Ruivo",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://pm1.narvii.com/6372/bc77672f7f807789b855ab1ca0615fcbc687d4e1_hq.jpg",
},
{
	id: 48,
	name: "Oars",
	specie: "Gigante",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Loiro",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://i.skyrock.net/7246/83337246/pics/3084726423_1_3_9D734wHj.jpg",
},
{
	id: 49,
	name: "Franky",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "South Blue",
	hairColor: "Azul",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/736x/c3/d2/be/c3d2be815f08b4547d30ec9b866ab27f.jpg",
},
{
	id: 50,
	name: "Iceburg",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Azul",
	occupation: "Outros",
	weapons: "false",
	color: colors.other,
	imgUrl: "https://cdn.anime-planet.com/characters/primary/iceburg-1-190x266.jpg?t=1625965603",
},
{
	id: 51,
	name: "Emporio Ivankov",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "Grand Line",
	hairColor: "Azul",
	occupation: "Revolucionário",
	weapons: "false",
	color: colors.revo,
	imgUrl: "http://vignette1.wikia.nocookie.net/onepiece/images/f/fc/Emporio_Ivankov_Portrait.png/revision/latest?cb=20130502210805",
},
{
	id: 52,
	name: "Portgas D. Ace",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "South Blue",
	hairColor: "Preto",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://alternativanerd.com.br/wp-content/uploads/2020/02/AN_Ace.jpg",
},
{
	id: 53,
	name: "Killer",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "South Blue",
	hairColor: "Loiro",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://i0.wp.com/alternativanerd.com.br/wp-content/uploads/2020/09/AN_Killer.jpg?fit=640%2C356&ssl=1",
},
{
	id: 54,
	name: "Sengoku (Buda)",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "South Blue",
	hairColor: "Preto",
	occupation: "Marinha",
	weapons: "false",
	color: colors.navy,
	imgUrl: "https://i.pinimg.com/736x/b2/03/e2/b203e276570538ce9395eafd8d9bcdb8.jpg",
},
{
	id: 55,
	name: "Don Chinjao",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "West Blue",
	hairColor: "Branco",
	occupation: "Outros",
	weapons: "false",
	color: colors.other,
	imgUrl: "http://pm1.narvii.com/7463/b5a0ac3d0c80f4d78e64b228986be6ea84e69d68r1-800-450v2_00.jpg",
},
{
	id: 56,
	name: "Daz Bones",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "West Blue",
	hairColor: "Branco",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://www.personality-database.com/profile_images/38864.png",
},
{
	id: 57,
	name: "Hack",
	specie: "Tritão",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Branco",
	occupation: "Revolucionário",
	weapons: "false",
	color: colors.revo,
	imgUrl: "https://cdn.myanimelist.net/r/360x360/images/characters/16/250467.jpg?s=7dd538a5311146bbdcbb13920eb9afe5",
},
{
	id: 58,
	name: "Koala",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Loiro",
	occupation: "Revolucionário",
	weapons: "false",
	color: colors.revo,
	imgUrl: "https://cdn.myanimelist.net/images/characters/16/391323.jpg",
},
{
	id: 59,
	name: "Duque Inuarashi",
	specie: "Mink",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Preto",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/originals/d1/52/d2/d152d2af59d7a8e4a4a5c25170040923.jpg",
},
{
	id: 60,
	name: "Edward Newgate",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "Novo Mundo",
	hairColor: "Branco",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://i.pinimg.com/736x/2b/53/a1/2b53a19516373c2262d0bb5ccd9910c8.jpg",
},
{
	id: 61,
	name: "Calgara",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Ruivo",
	occupation: "Outros",
	weapons: "true",
	color: colors.other,
	imgUrl: "https://64.media.tumblr.com/a4f1f36dde0c675d5f16a65f98c59ac2/98d4f55d4513ac11-8d/s250x400/4171e2c52299a3235dae861c7f38570115c966aa.png",
},
{
	id: 62,
	name: "Cabaji",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "East Blue",
	hairColor: "Verde",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "https://cdn.shopify.com/s/files/1/0549/2401/7706/articles/1_2c529905-9f4e-40c5-a76c-b6fec18b612d_1600x.jpg?v=1636917518",
},
{
	id: 63,
	name: "Denjiro",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Azul",
	occupation: "Outros",
	weapons: "true",
	color: colors.other,
	imgUrl: "https://cdn.myanimelist.net/images/characters/3/398118.jpg",
},
{
	id: 64,
	name: "Camie",
	specie: "Tritão",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Verde",
	occupation: "Outros",
	weapons: "false",
	color: colors.other,
	imgUrl: "https://i.pinimg.com/originals/95/d5/d9/95d5d964ad67d81f1c2a69e0871738d6.jpg",
},
{
	id: 65,
	name: "Coby",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "East Blue",
	hairColor: "Rosa",
	occupation: "Marinha",
	weapons: "false",
	color: colors.navy,
	imgUrl: "https://www.einerd.com.br/wp-content/uploads/2019/04/koby-one-piece-e1554209565592.jpg",
},
{
	id: 66,
	name: "Charlotte Linlin",
	specie: "Gigante",
	akumaNoMi: "true",
	origin: "Novo Mundo",
	hairColor: "Rosa",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://kanto.legiaodosherois.com.br/w728-h381-gnw-cfill-gcc-f:fbcover/wp-content/uploads/2021/02/legiao_cBfXSYqwJsi2.jpg.jpeg",
},
{
	id: 67,
	name: "Shirahoshi",
	specie: "Tritão",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Rosa",
	occupation: "Outros",
	weapons: "false",
	color: colors.other,
	imgUrl: "https://i.pinimg.com/originals/b3/b4/7b/b3b47bb0c4ffba7d0c2bcaf2fc4ae16b.jpg",
},
{
	id: 68,
	name: "Nekomamushi",
	specie: "Mink",
	akumaNoMi: "false",
	origin: "Novo Mundo",
	hairColor: "Loiro",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "http://pm1.narvii.com/6678/68f8a2b58f38d83ad6e71db22d15dc2a18115f67_00.jpg",
},
{
	id: 69,
	name: "Nefertari Vivi",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Azul",
	occupation: "Outros",
	weapons: "true",
	color: colors.other,
	imgUrl: "https://kanto.legiaodosherois.com.br/w1200-h628-cfill/wp-content/uploads/2020/09/legiao_kEh0jGAJB3O_.png.jpeg",
},
{
	id: 70,
	name: "Netuno",
	specie: "Tritão",
	akumaNoMi: "false",
	origin: "Grand Line",
	hairColor: "Ruivo",
	occupation: "Outros",
	weapons: "true",
	color: colors.other,
	imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvfX_6NQbUwNioNHUtrligFWOkzIdVF10tGqf4UOLUIEMfUvGXrzWRt3FTug18bxrlsnU&usqp=CAU",
},
{
	id: 71,
	name: "Buggy",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "East Blue",
	hairColor: "Azul",
	occupation: "Pirata",
	weapons: "true",
	color: colors.pirate,
	imgUrl: "http://pm1.narvii.com/7182/8dcbdef4307e039dadf7c0924793dc98e1d85d87r1-640-480v2_uhq.jpg",
},
{
	id: 72,
	name: "Patty",
	specie: "Humano",
	akumaNoMi: "false",
	origin: "East Blue",
	hairColor: "Azul",
	occupation: "Outros",
	weapons: "true",
	color: colors.other,
	imgUrl: "https://i0.wp.com/i.skyrock.net/4238/87434238/pics/3222272405_1_12_gNaf1hYa.jpg",
},
{
	id: 73,
	name: "Jewelry Bonney",
	specie: "Humano",
	akumaNoMi: "true",
	origin: "South Blue",
	hairColor: "Rosa",
	occupation: "Pirata",
	weapons: "false",
	color: colors.pirate,
	imgUrl: "https://64.media.tumblr.com/362077f94dc64417d8f023fcce12511d/ede8e3f7232a67b8-7f/s1280x1920/f1e323d6227a9f5d49fa38988a685c7d6f6c6892.jpg",
},
]

export default charData;